<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Wisata;

class WisataTrenggalekSeeder extends Seeder
{
    public function run()
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Wisata::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            // ============================================================
            // WISATA ALAM UTAMA (MAIN NATURAL TOURISM ATTRACTIONS)
            // ============================================================

            [
                'nama'           => 'Pantai Prigi',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Watulimo',
                'latitude'    => -8.2867561,  // ← FIX: dari -8.2828 (tengah laut) → area parkir pantai
                'longitude'   => 111.7258702,  // ← FIX: dari 111.7289
                'harga_tiket'    => 10000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '18:00',
                'fasilitas'      => 'Pantai, kuliner seafood, taman, parkir, area bermain, lapangan voli pantai, motocross',
                'hotel_terdekat' => 'Hotel Prigi, Pondok Prigi Cottage',
                'gambar'         => 'https://beautyofindonesia.com/asset-user/uploads/foto_wisata/PANTAI-PRIGI-KABUPATEN-TRENGGALEK.jpg',
                'deskripsi'      => 'Pantai Prigi terletak di Desa Tasikmadu, Kecamatan Watulimo, Kabupaten Trenggalek, kurang lebih 39 km Timur Laut Kota Trenggalek. Pantai Prigi merupakan destinasi wisata inklusif yang sangat menarik karena menyajikan pemandangan alam yang indah dengan fasilitas dan pusat kuliner yang inklusif dan nyaman. Aktivitas rekreasi: jogging sambil menikmati taman, hamparan pasir, bermain air, bermain layang-layang, voli pantai, kuliner seafood, dan motocross.',
            ],

            [
                'nama'           => 'Pantai Pasir Putih Karanggongso',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Watulimo',
                'latitude'    => -8.2978744,
    'longitude'   => 111.7392435,
                'harga_tiket'    => 15000,
                'rating'         => 4.8,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '18:00',
                'fasilitas'      => 'Banana boat, snorkeling, perahu wisata, pasir putih, kuliner seafood, parkir',
                'hotel_terdekat' => 'Hotel Prigi, Pondok Prigi Cottage, Hotel Logano, Hotel Karanggongso',
                'gambar'         => 'https://sidita.disbudpar.jatimprov.go.id/storage/foto-dtw/d4315_1708912323.jpg',
                'deskripsi'      => 'Pantai Pasir Putih Karanggongso terletak di Desa Tasikmadu, Kecamatan Watulimo, Kabupaten Trenggalek, sekitar 4 km di sebelah timur Pantai Prigi. Bagi penggemar pantai, Pasir Putih Karanggongso merupakan surga karena wisatawan bisa berenang, naik perahu wisata, naik banana boat, dan snorkeling di tengah ombak yang nyaman dengan hamparan pasir putih, bersih dan teduh. Kuliner seafood tersedia di sini.',
            ],

            [
                'nama'           => 'Pantai Mutiara',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Watulimo',
                'latitude'    => -8.3188097,   // ← FIX: dari -8.2870 (terlalu ke laut)
    'longitude'   => 111.7443516,
                'harga_tiket'    => 10000,
                'rating'         => 4.7,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Snorkeling, paddling, perahu wisata, canoe, rumah apung, homestay, parkir',
                'hotel_terdekat' => 'Hotel Prigi, Pondok Prigi Cottage',
                'gambar'         => 'https://getlost.id/wp-content/uploads/2021/04/@ilhamchalimi_.jpeg',
                'deskripsi'      => 'Pantai Mutiara berlokasi di Desa Tasikmadu, Kecamatan Watulimo, Kabupaten Trenggalek, tepatnya sekitar 4 km sebelah timur Pantai Pasir Putih Karanggongso. Bagi wisatawan yang lebih menyukai suasana tidak terlalu ramai, Pantai Mutiara merupakan tempat rekreasi yang cocok karena pantai ini indah, berpasir putih, bersih, dan ombaknya tenang. Tersedia banyak aktivitas air: perahu wisata, canoeing, paddling, dan rumah apung. Di rumah apung wisatawan juga bisa menikmati snorkeling dan kuliner. Tersedia paket wisata: Paket 1 (1 hari) IDR 225.000/orang min 5 orang; Paket 2 (1 hari 1 malam) IDR 200.000/orang min 5 orang.',
            ],

            [
                'nama'           => 'Pantai Simbaronce',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Watulimo',
                'latitude'    => -8.3011,
'longitude'   => 111.7414,
                'harga_tiket'    => 10000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai, parkir',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://static.promediateknologi.id/crop/0x434:1080x1036/0x0/webp/photo/p2/74/2025/01/12/Screenshot_20250112_094746-743767957.jpg',
                'deskripsi'      => 'Pantai Simbaronce berada di kawasan Watulimo dekat Pantai Prigi. Salah satu pantai yang masuk dalam kawasan wisata Watulimo Kondang.',
            ],

            [
                'nama'           => 'Pantai Damas',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Watulimo',
                 'latitude'    => -8.3259,
'longitude'   => 111.6915,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai alami, parkir, pemandu lokal',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://assets.pikiran-rakyat.com/crop/0x0:0x0/x/photo/2025/01/02/1290503326.jpg',
                'deskripsi'      => 'Pantai Damas terletak di Desa Karanggandu, Kecamatan Watulimo, berjarak 43,7 km dari Kota Trenggalek atau 8,6 km sebelah barat Pantai Prigi. Bagi wisatawan pencinta situasi yang alami dan tenang, Pantai Damas merupakan destinasi favorit karena pantainya masih alami, pemandangannya indah dan belum terlalu dikunjungi. Aktivitas: swafoto dengan background Samudra Hindia, bermain pasir, mandi di pantai dengan pengawasan pemandu.',
            ],

            [
                'nama'           => 'Hutan Mangrove Cengkrong',
                'kategori'       => 'Hutan',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2750,
                'longitude'      => 111.7150,
                'harga_tiket'    => 10000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Jembatan kayu, perahu, edukasi ekowisata, homestay/glamping camp, mushola, makan, parkir, wahana adventure, transportasi event',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://sidita.disbudpar.jatimprov.go.id/storage/foto-dtw/52e1b_1708922197.jpg',
                'deskripsi'      => 'Hutan Mangrove Cengkrong menawarkan banyak atraksi bagi wisatawan: jogging di jembatan kayu yang melintas di tengah hutan mangrove, swafoto dengan objek gunung, menikmati indahnya hutan mangrove, naik perahu menyusuri sungai dalam hutan mangrove jika air laut pasang, memberi makan burung dara, dan budidaya kepiting. Dengan konsep pengelola ekowisata, destinasi ini sangat menarik untuk dikunjungi.',
            ],

            [
                'nama'           => 'Desa Wisata Duren Sari (Durensari)',
                'kategori'       => 'Desa Wisata',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.3000,
                'longitude'      => 111.7100,
                'harga_tiket'    => 270000,
                'rating'         => 4.6,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Outbound, rivertubing, petik durian, homestay, kuliner khas desa, tour guide, souvenir',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://visit.trenggalekkab.go.id/assets/foto_destinasi/file_1675651588.jpg',
                'deskripsi'      => 'Desa Wisata Durensari berlokasi di Desa Sawahan, Kecamatan Watulimo, berjarak 38 km dari pusat kota Trenggalek atau 7,6 km dari Pantai Prigi. Bagi wisatawan keluarga dan kelompok, Desa Wisata Durensari sangat menarik. Aktivitas: outbound, rivertubing, petik durian, stone balancing, gerduren, edukasi pembuatan reyang & angklung bambu, permainan tradisional, eksplorasi Pantai Pasir Putih. Paket 1 (1 hari) IDR 270.000/orang min 8 orang; Paket 2 (1 hari 1 malam) IDR 375.000/orang; Paket 3 (2 hari 1 malam) IDR 490.000/orang; Paket 4 (3 hari 2 malam) IDR 785.000/orang. Kontak: 082147714390, IG: @desawisatadurensari.',
            ],

            [
                'nama'           => 'Goa Lowo',
                'kategori'       => 'Goa',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2435,
                'longitude'      => 111.7210,
                'harga_tiket'    => 10000,
                'rating'         => 4.7,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Lampu penerangan goa, pemandu wisata, parkir, kawasan hutan jati dan karst',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://thumb.viva.id/vivawisata/665x374/2024/12/09/67566bb343374-goa-lowo_wisata.jpg',
                'deskripsi'      => 'Goa Lowo berlokasi di Desa Watuagung, Kecamatan Watulimo, 23,7 km arah Tenggara dari pusat Kota Trenggalek. Ditemukan tahun 1931, dan menurut penelitian ahli Goa dari Perancis Gilbert Mantovani dan Kingston Kho (1985), Goa Lowo dinyatakan sebagai gua terbesar dan terpanjang se-Asia Tenggara. Goa ini memiliki ruangan yang panjang dan sangat luas dihiasi stalaktit dan stalagmit aktif yang sangat indah dengan lighting yang menambah daya tarik. Berada di kawasan hutan jati dan karst.',
            ],

            [
                'nama'           => 'Pantai Kili-Kili',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Panggul',
                'latitude'    => -8.2596,
'longitude'   => 111.4304,
                'harga_tiket'    => 5000,
                'rating'         => 4.7,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Konservasi penyu, swafoto, pemandu lokal',
                'hotel_terdekat' => 'Hotel Ratu Panggul',
                'gambar'         => 'https://cdn.timesmedia.co.id/images/2020/02/25/Pantai-Taman-Kili-kili.jpg',
                'deskripsi'      => 'Pantai Kili-Kili berada di Desa Wonocoyo, Kecamatan Panggul, Kabupaten Trenggalek, berjarak sekitar 54 km sebelah barat daya kota Trenggalek. Pantai ini merupakan kawasan ekosistem esensial dengan konservasi penyu. Wisatawan bisa menikmati pemandangan pantai yang indah, swafoto dengan penyu, dan memperoleh pengetahuan tentang penyu dari pemandu setempat. Bahkan jika memungkinkan, wisatawan bisa melakukan adopsi tukik. Akses yang masih alami menjadi daya tarik tersendiri.',
            ],

            [
                'nama'           => 'Pantai Pelang',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Panggul',
               'latitude'    => -8.2578,
'longitude'   => 111.4239,
                'harga_tiket'    => 8000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Air terjun, pantai, parkir, pemandu lokal',
                'hotel_terdekat' => 'Hotel Ratu Panggul, Hotel Sanra',
                'gambar'         => 'https://sidita.disbudpar.jatimprov.go.id/storage/foto-dtw/b1a5d_1708915199.jpg',
                'deskripsi'      => 'Pantai Pelang berlokasi di Desa Wonocoyo, Kecamatan Panggul, Kabupaten Trenggalek, berjarak 56 km sebelah barat pusat kota. Bagi wisatawan penggemar air terjun dan panorama pantai, Pantai Pelang sangat menarik karena memiliki pemandangan yang eksotis dan alami. Ada air terjun yang cantik di dekat muara sungai yang menjadi tempat mandi dan bermain air. Selain itu jika beruntung, ada pemandangan menarik burung bangau putih yang terbang dari dan menuju pulau kecil nan indah tak jauh dari pantai yang mirip Tanah Lot.',
            ],

            [
                'nama'           => 'Pantai Konang',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Panggul',
                'latitude'    => -8.2748,
'longitude'   => 111.4529,
                'harga_tiket'    => 5000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '18:00',
                'fasilitas'      => 'Kuliner seafood, pasir luas, parkir',
                'hotel_terdekat' => 'Hotel Ratu Panggul, Hotel Pondok Konang',
                'gambar'         => 'https://ik.imagekit.io/tvlk/blog/2025/07/pantai-konang.jpg?tr=q-70,c-at_max,w-1000,h-600',
                'deskripsi'      => 'Pantai Konang bertempat di Desa Nglebeng, Kecamatan Panggul, berjarak sekitar 3 km sebelah timur Pantai Pelang. Pantai Konang memiliki garis pantai yang panjang dan ombak yang besar. Tempat ini memiliki pemandangan matahari terbenam yang sangat indah. Tersedia kuliner ikan laut yang sangat memanjakan wisatawan.',
            ],

            [
                'nama'           => 'Pantai Kuyon (Desa Wisata Nglebeng)',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Panggul',
               'latitude'    => -8.2963,
'longitude'   => 111.4496,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai alami, perahu, wisata desa, kuliner khas, aktivitas nelayan',
                'hotel_terdekat' => 'Hotel Ratu Panggul',
                'gambar'         => 'https://cdn-jpr.jawapos.com/images/43/2025/07/28/WhatsApp-Image-2025-07-28-at-163437-4279761914.jpeg',
                'deskripsi'      => 'Pantai Kuyon merupakan destinasi wisata baru yang dioperatori oleh Kelompok Sadar Wisata Suka Maju, Desa Wisata Nglebeng, Kecamatan Panggul. Setelah menempuh perjalanan yang agak menguji adrenaline, wisatawan akan menikmati keindahan pemandangan Pantai Kuyon yang masih alami. Untuk kenyamanan, wisatawan kelompok dapat menghubungi contact person operator di 082139343830. Aktivitas: menarik jaring bersama nelayan, berjalan-jalan menyusuri bibir pantai, memasak dan menikmati kuliner khas.',
            ],

            [
                'nama'           => 'Pantai Rajaan',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
                    'latitude'    => -8.3247,
'longitude'   => 111.5060, 
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pemandangan karang, sunset, pemandu lokal (wajib)',
                'hotel_terdekat' => 'Hotel Ratu Panggul',
                'gambar'         => 'https://cdn-1.timesmedia.co.id/images/2022/08/09/Pemandangan-bebatuan-di-Pantai-Rajaan.jpg',
                'deskripsi'      => 'Pantai Rajaan merupakan pantai cantik yang terletak di Desa Ngulungkulon, Kecamatan Munjungan. Meskipun belum dikelola, pantai ini memiliki pemandangan yang sangat eksotis dan cukup menantang bagi wisatawan yang berjiwa petualang. Untuk menuju pantai ini, wisatawan sangat disarankan menghubungi pemandu wisata setempat. Aktivitas: menikmati keindahan pantai, selfie dengan objek gambar pantai, dan mandi di tepi pantai dengan pemantauan pemandu.',
            ],

            [
                'nama'           => 'Pantai Kebo',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
               'latitude'    => -8.3062,
'longitude'   => 111.4814,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Laguna, perahu/kayak/canoe, pengembala kerbau, parkir',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://travelspromo.com/wp-content/uploads/2024/10/Pemandangan-Pantai-Kebo-yang-berpasir-putih-Arif-Usman.jpg',
                'deskripsi'      => 'Pantai Kebo terletak di desa Ngulung Wetan, Kecamatan Munjungan. Pantai ini sangat menawan karena memiliki hamparan pasir yang luas dan landai dengan pemandangan hijaunya pegunungan di sebelah utara dan birunya Samudra Hindia di sebelah selatan. Keunikan pantai ini adalah memiliki laguna yang airnya dikelilingi dapat dimanfaatkan untuk olahraga air seperti kayak dan perahu wisata. Para kawanan kerbau yang digembala oleh pengembala di sekitar laguna dan muara sungai menjadi atraksi wisata menarik. Aktivitas: melihat pemandangan, bermain pasir, menarik jaring, bermain perahu/kayak/canoe, mengembala dan naik kerbau, berkemah.',
            ],

            [
                'nama'           => 'Pantai Blado',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.3159115,
                'longitude'      => 111.5728589,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai panjang, jogging, swafoto, kemah, kuliner khas Munjungan, pemandu lokal',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://i2.wp.com/is3.cloudhost.id/img-kbrt/2022/08/Indahnya-wisata-Pantai-Blado-Munjungan-Trenggalek-.jpg',
                'deskripsi'      => 'Pantai Blado memiliki garis pantai yang sangat panjang yang membentang dari Desa Munjungan sampai Desa Masaran, Kecamatan Munjungan. Pantai Blado menawarkan pemandangan pantai selatan yang indah. Juga tempat diselenggarakannya Upacara Adat Longkangan di Kecamatan Munjungan pada bulan Selo hari Jumat Kliwon. Disarankan menggunakan pemandu lokal.',
            ],

            [
                'nama'           => 'Pantai Ngampiran',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
'latitude'    => -8.3282,
'longitude'   => 111.6075,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai alami, pasir putih, pemandu lokal (disarankan)',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://cdn.suaranetwork.com/images/2024/12/17/2937acb7c51e.jpg',
                'deskripsi'      => 'Pantai Ngampiran berada di Desa Tawing, Kecamatan Munjungan, sekitar 4 km arah Timur laut dari pusat Kecamatan Munjungan atau sekitar 50 km barat daya dari Kota Trenggalek. Pantai Ngampiran masih alami serta memiliki pasir putih. Ombaknya tidak terlalu besar sehingga dengan pemantauan pemandu, wisatawan bisa mandi di pantai. Aktivitas: berswa foto dengan background pemandangan pantai dan perahu-perahu nelayan. Bagi wisatawan yang menyukai suasana tenang, pantai ini cukup cocok karena pengunjungnya tidak terlalu ramai.',
            ],

            [
                'nama'           => 'Coban Wonoasri',
                'kategori'       => 'Air Terjun',
                'kecamatan'      => 'Munjungan',
                'latitude'    => -8.2793,
'longitude'   => 111.6359,
                'harga_tiket'    => 5000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Air terjun alami, akses motor, kamar mandi, swafoto, pemandu lokal',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgeaeNwqXTsubl921JSeIMnXDCnU9nxgsV3lKlijW7kesNDj0NLftbROXatL_Pvk6lkwscsM-QhbCwRv2VEegizKOqOJ4uGz06xOgKAaFBSZGkVk6zEUzWrq6fbkCcAOrwZBrY4Xr1lPIs/s1600/IMG_20180108_100804.jpg',
                'deskripsi'      => 'Coban Wonoasri berada di Desa Bangun, Kecamatan Munjungan. Air terjun ini masih alami dan menawarkan pemandangan indah alam di sekitarnya. Wisatawan bisa menikmati jernihnya dan dinginnya air pegunungan di coban ini. Pengelola juga menyediakan sarana/atraksi untuk swafoto. Fasilitas: akses untuk sepeda motor dan kamar mandi. Untuk menikmati destinasi wisata ini, diharapkan wisatawan menggunakan jasa pemandu lokal.',
            ],

            [
                'nama'           => 'Tebing Lingga',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Suruh',
                'latitude'       => -8.1000,
                'longitude'      => 111.8000,
                'harga_tiket'    => 10000,
                'rating'         => 4.6,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Camping/glamping, panjat tebing, homestay, kuliner lokal, pemandu wisata lokal, scenic tourism, susur sungai, belajar ternak kambing perah, belajar gamelan tradisional, star gazing',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'https://awsimages.detik.net.id/community/media/visual/2022/10/30/destinasi-wisata-di-trenggalek-2.jpeg?w=650&q=90',
                'deskripsi'      => 'Wisata Tebing Lingga terletak di Desa Nglebo, Kecamatan Suruh, sekitar 19 km sebelah barat kota Trenggalek. Atraksi wisata utama destinasi ini adalah gunung batu andesit terbesar di dunia dengan ketinggian 360 m dan kemiringan nyaris 90°. Pernah dipakai latihan panjat tebing oleh KOPASUS dan pernah dipanjat oleh pemanjat tebing dari dalam maupun luar negeri. Untuk wisatawan keluarga, tempat ini sangat menarik karena dapat menikmati kemegahan "Tebing Lingga" dari dekat dan berbagai aktivitas rekreasi keluarga. Paket 2 hari 1 malam: 5 orang IDR 2.954.000; 6-10 orang IDR 3.971.000; 11-15 orang IDR 5.154.000. Contact: +62 555-5856-6481 / +62 895-4306-4855.',
            ],

            [
                'nama'           => 'Ngerit Stone Park',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Kampak',
                'latitude'       => -8.1200,
                'longitude'      => 111.6500,
                'harga_tiket'    => 10000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Taman batu karst, sungai, swafoto, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Ngerit Stone Park terletak di Desa Senden, Kecamatan Kampak, berjarak 20 km dari pusat Kota Trenggalek. Ngerit Stone Park merupakan taman yang indah dari batu-batu karst. Di tengah-tengah taman batu tersebut mengalir sungai yang gemericik airnya yang semakin menambah keasrian destinasi wisata ini. Selain menikmati keindahan taman karst ini, wisatawan juga bisa melakukan swafoto, memperoleh pengetahuan tentang karst dan juga cerita rakyat tentang taman karst tersebut.',
            ],

            [
                'nama'           => 'Bukit Paralayang Tunggangan',
                'kategori'       => 'Bukit',
                'kecamatan'      => 'Durenan',
                'latitude'       => -8.1000,
                'longitude'      => 111.8300,
                'harga_tiket'    => 350000,
                'rating'         => 4.8,
                'jam_buka'       => '06:00',
                'jam_tutup'      => '18:00',
                'fasilitas'      => 'Paralayang/ganthole, camping ground glam camp (1 Ha, 24 jam), toilet, parkir, foodcourt kuliner lokal',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Bukit Paralayang Tunggangan berada di Dusun Ngrandu, Desa Kendalrejo, Kecamatan Durenan, Trenggalek, dengan luas area 20 Ha dan ketinggian 250 mdpl. Wisatawan dapat menyaksikan matahari terbit. Bukit ini juga menyuguhkan sensasi seolah-olah berada di atas awan. Bukit ini juga merupakan satu-satunya base spot olahraga paralayang dan ganthole di Trenggalek yang sudah teruji secara nasional. Harga paralayang: IDR 350.000/flight, buka setiap Sabtu-Minggu, minimal 3 orang. Booking: WA 081 234 636 666. Glam camp: tersedia area seluas 1 Ha, buka 24 jam. Tarif parkir: motor IDR 10.000, mobil IDR 20.000.',
            ],

            [
                'nama'           => 'Bukit Banyon',
                'kategori'       => 'Bukit',
                'kecamatan'      => 'Gandusari',
                'latitude'       => -8.0800,
                'longitude'      => 111.7600,
                'harga_tiket'    => 5000,
                'rating'         => 4.8,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Spot sunrise, camping, pemandangan malam kota',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Bukit Banyon lebih viral dengan sebutan "Negeri di Atas Awan". Pada pagi hari musim kabut, seluruh daerah di kaki Bukit Banyon diselimuti oleh kabut tebal sehingga ketika wisatawan berada di atas bukit, mereka akan merasakan sensasi berada di atas awan. Di malam hari, Bukit Banyon juga menawarkan pemandangan lampu yang sangat indah yang ada di daerah-daerah sekitar bukit, bahkan kota Trenggalek. Dengan jarak yang tidak jauh dari kota, destinasi ini sangat recommended untuk dikunjungi.',
            ],

            [
                'nama'           => 'Argowisata Dilem Wilis',
                'kategori'       => 'Agrowisata',
                'kecamatan'      => 'Bendungan',
                'latitude'       => -7.9500,
                'longitude'      => 111.7800,
                'harga_tiket'    => 10000,
                'rating'         => 4.6,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Kebun bunga, kebun buah, sapi perah & pengolahan susu, pabrik kopi heritage Belanda, cafetoria kopi khas Bendungan, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Argowisata Dilem Wilis merupakan destinasi wisata agro di Trenggalek yang juga merupakan satu-satunya wisata heritage. Berlokasi di Desa Dompyong, Kecamatan Bendungan, yang merupakan bagian dari kawasan strategis selingkar Wilis, dengan luas 228.123 Ha. Menawarkan panorama alam pegunungan yang indah dengan udara yang sejuk. Atraksi: kebun bunga, kebun buah, sapi perah dan pengolahan susu, pabrik kopi peninggalan Belanda, dan menikmati kopi khas Bendungan di cafetoria yang sudah disediakan.',
            ],

            // ============================================================
            // WISATA ALAM ALTERNATIF
            // ============================================================

            [
                'nama'           => 'Dilem Wilis (Wisata Perkebunan)',
                'kategori'       => 'Agrowisata',
                'kecamatan'      => 'Bendungan',
                'latitude'       => -7.9400,
                'longitude'      => 111.7700,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Perkebunan, pemandangan alam, udara sejuk',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Kawasan wisata perkebunan di Bendungan, Trenggalek, dengan panorama alam pegunungan Wilis yang memukau.',
            ],

            [
                'nama'           => 'Coban Rambat',
                'kategori'       => 'Air Terjun',
                'kecamatan'      => 'Bendungan',
               'latitude'    => -7.9388,
'longitude'   => 111.7099,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Air terjun alam, tracking',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'https://cdn.timesmedia.co.id/images/2020/02/26/Coban-Rambat.jpg',
                'deskripsi'      => 'Coban Rambat merupakan air terjun alami yang berada di kawasan Bendungan, Trenggalek. Destinasi alam yang cocok untuk wisatawan pecinta alam dan tracking.',
            ],

            [
                'nama'           => 'Putri Maron',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Bendungan',
                'latitude'       => -7.9800,
                'longitude'      => 111.7600,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Alam pegunungan, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Putri Maron merupakan destinasi wisata alam di kawasan Bendungan, Trenggalek, menawarkan pemandangan pegunungan yang indah.',
            ],

            [
                'nama'           => 'Air Terjun Songgo Langit',
                'kategori'       => 'Air Terjun',
                'kecamatan'      => 'Suruh',
'latitude'    => -8.0653,
'longitude'   => 111.5894,
                'harga_tiket'    => 5000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Air terjun alam, tracking',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'https://www.gresiksatu.com/wp-content/uploads/2024/07/air-terjun-songgo-langit.jpg',
                'deskripsi'      => 'Air Terjun Songgo Langit berada di Kecamatan Suruh, Trenggalek. Destinasi alam yang menawarkan keindahan air terjun alami di tengah pegunungan.',
            ],

            [
                'nama'           => 'Argo Lawi (Argo Park)',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Pule',
                'latitude'       => -8.1100,
                'longitude'      => 111.7900,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Taman pertanian, wahana edukasi anak',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Argo Lawi (Argo Park) merupakan taman pertanian terpadu yang merupakan wahana wisata edukasi bagi anak-anak, berlokasi di Pule, Trenggalek.',
            ],

            [
                'nama'           => 'Beji Maron',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Gandusari',
                'latitude'       => -8.0700,
                'longitude'      => 111.7700,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Mata air, alam, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Beji Maron merupakan wisata alam berupa mata air yang terdapat di Kecamatan Gandusari, Trenggalek.',
            ],

            [
                'nama'           => 'Gunung Sepikul / Via Ferrata',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Kampak',
                'latitude'       => -8.1400,
                'longitude'      => 111.6700,
                'harga_tiket'    => 10000,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Via ferrata, pendakian, pemandangan alam',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Gunung Sepikul menawarkan wisata via ferrata (panjat tebing dengan tangga besi) di Kecamatan Kampak, Trenggalek. Cocok untuk wisatawan pecinta petualangan.',
            ],

            [
                'nama'           => 'Goa Ngerit',
                'kategori'       => 'Goa',
                'kecamatan'      => 'Kampak',
                'latitude'       => -8.1300,
                'longitude'      => 111.6600,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Goa alam, pemandu',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'https://sidita.disbudpar.jatimprov.go.id/storage/foto-dtw/eab1c_1708922827.jpg',
                'deskripsi'      => 'Goa Ngerit merupakan goa alam yang berada di kawasan Kampak, Trenggalek, dekat dengan Ngerit Stone Park.',
            ],

            [
                'nama'           => 'Wisata Banyunget',
                'kategori'       => 'Alam',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2600,
                'longitude'      => 111.7000,
                'harga_tiket'    => 5000,
                'rating'         => 4.3,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Wisata alam, parkir',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Wisata Banyunget merupakan destinasi wisata alam yang terletak di kawasan Watulimo, Trenggalek.',
            ],

            [
                'nama'           => 'Pantai Ngulungwetan',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4200,
                'longitude'      => 111.5050,
                'harga_tiket'    => 5000,
                'rating'         => 4.3,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai alami, pemandu lokal',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://ngulungwetan-munjungan.trenggalekkab.go.id/assets/files/artikel/sedang_1549277909IMG-20190204-WA0008.jpg',
                'deskripsi'      => 'Pantai Ngulungwetan berada di Kecamatan Munjungan, Trenggalek. Pantai alami dengan suasana yang tenang dan jarang dikunjungi.',
            ],

            [
                'nama'           => 'Pantai Ngadipuro',
                'kategori'       => 'Pantai',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4600,
                'longitude'      => 111.4850,
                'harga_tiket'    => 5000,
                'rating'         => 4.3,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pantai alami, pemandu lokal',
                'hotel_terdekat' => 'Omah Blado Resort',
                'gambar'         => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEip9fs4PLOXucpzyicL_4zOsgWKSRDJ2qCz-lQgDYE-xJ5tFx33MFW944OSeJrXmIQ0bYoEUYF4plM21WK0szRofTeVbtEtrLVhM38wJeajXhFjwFsq2TUApyj-zMKc81CuzZab6fGarsh9/s1600/info-trenggalek.blogspot.co.id+-+pantai+ngadipuro+2.jpg',
                'deskripsi'      => 'Pantai Ngadipuro merupakan pantai alami di Kecamatan Munjungan, Trenggalek, yang masih belum banyak dikunjungi wisatawan.',
            ],

            // ============================================================
            // WISATA BUATAN (MAN-MADE / URBAN TOURISM)
            // ============================================================

            [
                'nama'           => 'Green Park Trenggalek',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0580,
                'longitude'      => 111.7120,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Taman, area bermain anak, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk, Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Green Park merupakan taman kota Trenggalek yang menyuguhkan taman dan tempat bermain bagi anak. Destinasi wisata keluarga yang terletak di jantung kota Trenggalek.',
            ],

            [
                'nama'           => 'Argo Park (Taman Pertanian Kota)',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0570,
                'longitude'      => 111.7110,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Taman pertanian terpadu, wahana edukasi anak',
                'hotel_terdekat' => 'Hotel Hayam Wuruk, Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Argo Park menyuguhkan taman pertanian terpadu yang merupakan wahana wisata edukasi bagi anak. Terletak di jantung kota Trenggalek bersama Green Park dan Hutan Kota.',
            ],

            [
                'nama'           => 'Hutan Kota Trenggalek',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0560,
                'longitude'      => 111.7100,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '06:00',
                'jam_tutup'      => '18:00',
                'fasilitas'      => 'Jogging track, satwa dilindungi (merak/kijang/kasuari), track downhill, udara sejuk',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hutan Kota menyuguhkan atraksi udara sejuk dan bersih di tengah-tengah kota, satwa dilindungi seperti merak, kijang, dan burung kasuari, serta area jogging track yang dapat dimanfaatkan wisatawan untuk jogging. Di kawasan Hutan Kota ini juga terdapat track downhill yang menarik.',
            ],

            [
                'nama'           => 'Kolam Renang Tirta Jwalita',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0620,
                'longitude'      => 111.7140,
                'harga_tiket'    => 10000,
                'rating'         => 4.3,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Kolam renang, fasilitas memadai, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk, Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Kolam Renang Tirta Jwalita merupakan kolam renang yang dikelola Pemerintah Kabupaten Trenggalek, berlokasi di tengah-tengah kota, tepatnya di Jl. Soekarno-Hatta, Kelutan, Trenggalek. Di kolam renang ini sudah tersedia fasilitas-fasilitas yang memadai.',
            ],

            [
                'nama'           => 'Caribean Water Park',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0590,
                'longitude'      => 111.7130,
                'harga_tiket'    => 25000,
                'rating'         => 4.3,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Waterpark, wahana air, parkir, kantin',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Caribean Water Park merupakan destinasi wisata air yang berlokasi di pusat kota Trenggalek, cocok untuk wisata keluarga dan anak-anak.',
            ],

            [
                'nama'           => 'Taman Pantai Prigi',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2825,
                'longitude'      => 111.7285,
                'harga_tiket'    => 5000,
                'rating'         => 4.4,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Taman, gazebo, spot foto, parkir',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://travelspromo.com/wp-content/uploads/2020/09/Taman-di-Pantai-Prigi.-Foto-Gmap-STUDIO-ONE-MADIUN.jpg',
                'deskripsi'      => 'Taman Pantai Prigi merupakan taman yang berada di kawasan Pantai Prigi, menawarkan suasana santai dengan taman yang asri dan spot foto yang menarik.',
            ],

            [
                'nama'           => 'Sport Center Trenggalek',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Tugu',
                'latitude'       => -8.0450,
                'longitude'      => 111.7080,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Fasilitas olahraga, lapangan, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Sport Center Trenggalek merupakan pusat olahraga yang terletak di Kecamatan Tugu, Trenggalek.',
            ],

            [
                'nama'           => 'Anjungan Cerdas (Rest Area)',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Karangan',
                'latitude'       => -8.0800,
                'longitude'      => 111.7600,
                'harga_tiket'    => 0,
                'rating'         => 4.1,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Rest area, kuliner, parkir, toilet',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Anjungan Cerdas merupakan rest area di Kecamatan Karangan, Trenggalek, yang menyediakan tempat beristirahat bagi wisatawan yang melakukan perjalanan.',
            ],

            [
                'nama'           => 'Pusat Oleh-Oleh Ngantru',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Tugu',
                'latitude'       => -8.0400,
                'longitude'      => 111.7050,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Toko oleh-oleh, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Pusat oleh-oleh di Ngantru, Trenggalek, menyediakan berbagai oleh-oleh khas Trenggalek seperti alen-alen, manco, geti, kopi Van Dilem, dan produk lokal lainnya.',
            ],

            [
                'nama'           => 'Pemandian Tapan',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Karangan',
                'latitude'       => -8.0900,
                'longitude'      => 111.7700,
                'harga_tiket'    => 5000,
                'rating'         => 4.2,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Pemandian, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Pemandian Tapan merupakan destinasi wisata air berupa pemandian alami yang berlokasi di Kecamatan Karangan, Trenggalek.',
            ],

            [
                'nama'           => 'Wisata Sawahan (Desa Wisata Duren Sari - area sawah)',
                'kategori'       => 'Desa Wisata',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.3050,
                'longitude'      => 111.7080,
                'harga_tiket'    => 10000,
                'rating'         => 4.4,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Wisata sawah, outbound, kuliner',
                'hotel_terdekat' => 'Hotel Prigi',
                'gambar'         => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTT4GJ34Skn7lG5kfDvdAn00RsXJX7Tgbco6DHIsIiroxLFzR572v2ZRcTEuxqpJYLC7gZ_Prc_MwEU1wRckRVhsWNWnr3GX2n-mZVGi7tLyAi3hRSXLk52DtgzpGluwrq21zgjJiYNscq/s1600/hotel-prigi-trenggalek.jpg',
                'deskripsi'      => 'Wisata Sawahan merupakan bagian dari kawasan Desa Wisata Duren Sari di Desa Sawahan, Kecamatan Watulimo. Menawarkan pengalaman wisata pedesaan dengan aktivitas sawah dan alam.',
            ],

            [
                'nama'           => 'Kraton/Istana Tilde Jwaltra',
                'kategori'       => 'Wisata Buatan',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0600,
                'longitude'      => 111.7130,
                'harga_tiket'    => 5000,
                'rating'         => 4.2,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Wisata budaya, spot foto, parkir',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Destinasi wisata buatan di pusat kota Trenggalek.',
            ],

            // ============================================================
            // ATRAKSI WISATA BUDAYA (CULTURAL TOURISM ATTRACTIONS)
            // ============================================================

            [
    
        'nama'               => 'Larung Sembonyo (Upacara Adat)',
        'kategori'           => 'Budaya',
        'kecamatan'          => 'Watulimo',
        'latitude'           => -8.2828,
        'longitude'          => 111.7289,
        'harga_tiket'        => 0,
        'rating'             => 4.8,
        'jam_buka'           => '',
        'jam_tutup'          => '',
        'tanggal_pelaksanaan' => 'Senin Kliwon di Bulan Selo (Penanggalan Jawa)',
        'fasilitas'          => 'Atraksi budaya tahunan, pawai karnaval, kesenian, prosesi adat, pelelangan ikan',
        'hotel_terdekat'     => 'Hotel Prigi',
        'gambar'             => 'https://detikglobalnews.com/wp-content/uploads/2023/06/IMG-20230603-WA0226.jpg',
        'deskripsi'          => 'Upacara adat Larung Sembonyo dilaksanakan setiap tahun pada bulan Selo, tepatnya pada hari Senin Kliwon. Merupakan bentuk syukur nelayan Pantai Prigi atas hasil laut dan peringatan sejarah pernikahan Raden Tumenggung Yudho Negoro.',
    ],

    [
        'nama'               => 'Longkangan (Upacara Adat)',
        'kategori'           => 'Budaya',
        'kecamatan'          => 'Munjungan',
        'latitude'           => -8.4500,
        'longitude'          => 111.5000,
        'harga_tiket'        => 0,
        'rating'             => 4.7,
        'jam_buka'           => '',
        'jam_tutup'          => '',
        'tanggal_pelaksanaan' => 'Jumat Kliwon di Bulan Selo (Penanggalan Jawa)',
        'fasilitas'          => 'Atraksi budaya, prosesi adat nelayan, pertunjukan seni pesisir',
        'hotel_terdekat'     => 'Omah Blado Resort',
        'gambar'             => 'https://jatimnow.com/po-content/uploads/202306/whatsapp-image-2023-06-13-at-15.34.45.jpg',
        'deskripsi'          => 'Upacara Longkangan digelar rutin setiap tahun pada bulan Selo, tepatnya pada hari Jumat Kliwon di Pantai Blado. Tradisi ini memperingati jasa leluhur pembuka wilayah Munjungan serta ungkapan rasa syukur nelayan.',
    ],

    [
        'nama'               => 'Festival Turonggo Yakso / Festival Jaranan',
        'kategori'           => 'Budaya',
        'kecamatan'          => 'Trenggalek',
        'latitude'           => -8.0600,
        'longitude'          => 111.7130,
        'harga_tiket'        => 0,
        'rating'             => 4.8,
        'jam_buka'           => '',
        'jam_tutup'          => '',
        'tanggal_pelaksanaan' => 'Bulan Agustus (Rangkaian Hari Jadi)',
        'fasilitas'          => 'Festival budaya tahunan, pertunjukan jaranan, tata busana kreasi, koreografi, tata lampu panggung',
        'hotel_terdekat'     => 'Hotel Hayam Wuruk',
        'gambar'             => 'https://awsimages.detik.net.id/community/media/visual/2024/07/08/pemkab-trenggalek.jpeg?w=1200',
        'deskripsi'          => 'Digelar tahunan pada bulan Agustus. Festival ini merupakan kompetisi seni jaranan tingkat nasional, menampilkan Turonggo Yakso, kesenian asli Trenggalek yang melambangkan kemenangan manusia atas nafsu angkara murka.',
    ],

    [
        'nama'               => 'Hari Jadi Kabupaten Trenggalek',
        'kategori'           => 'Budaya',
        'kecamatan'          => 'Trenggalek',
        'latitude'           => -8.0610,
        'longitude'          => 111.7130,
        'harga_tiket'        => 0,
        'rating'             => 4.7,
        'jam_buka'           => '',
        'jam_tutup'          => '',
        'tanggal_pelaksanaan' => '31 Agustus (Tahunan)',
        'fasilitas'          => 'Kirap pusaka, seremonial, pagelaran wayang kulit semalam suntuk, ziarah makam leluhur',
        'hotel_terdekat'     => 'Hotel Hayam Wuruk',
        'gambar'         => 'https://thumb.viva.id/vivajatim/1265x711/2025/08/31/68b46509a9c73-proses-kirab-harjad-ke-831-kabupaten-trenggalek_jatim.jpg',
        'deskripsi'          => 'Puncak peringatan setiap tanggal 31 Agustus. Prosesi utama meliputi Kirab Pusaka menuju Pendhapa, penyajian tumpeng agung yang diperebutkan warga, serta pertunjukan wayang kulit semalam suntuk.',
    ],

    [
        'nama'               => 'Hari Raya Kupatan (Tradisi Durenan)',
        'kategori'           => 'Budaya',
        'kecamatan'          => 'Durenan',
        'latitude'           => -8.1000,
        'longitude'          => 111.8300,
        'harga_tiket'        => 0,
        'rating'             => 4.6,
        'jam_buka'           => '',
        'jam_tutup'          => '',
        'tanggal_pelaksanaan' => '8 Syawal (H+7 Idul Fitri)',
        'fasilitas'          => 'Tradisi kupatan, kirap gunungan ketupat, musik hadroh/rebana, silaturahmi warga',
        'hotel_terdekat'     => 'Hotel Hayam Wuruk',
        'gambar'             => 'https://awsimages.detik.net.id/community/media/visual/2019/06/12/0c4b5263-0e6f-4e1d-ad81-5e3b132dced6_169.jpeg?w=620',
        'deskripsi'          => 'Dilaksanakan tepat pada tanggal 8 Syawal. Tradisi unik di mana setiap rumah di Durenan menyediakan hidangan ketupat secara gratis bagi tamu, dimeriahkan dengan kirab gunungan ketupat.',
    ],


            // ============================================================
            // HOTEL / PENGINAPAN
            // ============================================================

            [
                'nama'           => 'Hotel Prigi',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2830,
                'longitude'      => 111.7280,
                'harga_tiket'    => 0,
                'rating'         => 4.5,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Airphone, Ruang Tamu, Air Panas, Parkir, Ruang Pertemuan, Restoran, Lapangan Tenis',
                'hotel_terdekat' => '-',
                'gambar'         => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTT4GJ34Skn7lG5kfDvdAn00RsXJX7Tgbco6DHIsIiroxLFzR572v2ZRcTEuxqpJYLC7gZ_Prc_MwEU1wRckRVhsWNWnr3GX2n-mZVGi7tLyAi3hRSXLk52DtgzpGluwrq21zgjJiYNscq/s1600/hotel-prigi-trenggalek.jpg',
                'deskripsi'      => 'Hotel Prigi berlokasi di Pantai Prigi, Kecamatan Watulimo. Telp: 0355-551180. Jumlah kamar: 26.',
            ],

            [
                'nama'           => 'Pondok Prigi Cottage',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2860,
                'longitude'      => 111.7225,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Airphone, Ruang Tamu, Air Panas, Parkir, Ruang Pertemuan, Restoran, Lapangan Tenis',
                'hotel_terdekat' => '-',
                'gambar'         => 'https://visit.trenggalekkab.go.id/assets/foto_akomodasi/file_1770172840.jpg',
                'deskripsi'      => 'Pondok Prigi Cottage berlokasi di Pantai Karanggongso, Kecamatan Watulimo. Telp: 0355-551187. Jumlah kamar: 17.',
            ],

            [
                'nama'           => 'Hotel Logano',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2865,
                'longitude'      => 111.7228,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg-VqOrnV9Y1TLRNKsqlq1iXBSv4XX52HUAB7XtL6JRpREUGGUwIOBz1pSwcvtTs475LBp4R9NffECwwUrtuYhR2XW5B7uvm0cap5SPvlZkba1BRqXHXY-ygMIoIK0QRd9GG9M3-n2jjGQ/s1600/hotel+logano+trenggalek.jpg',
                'deskripsi'      => 'Hotel Logano berlokasi di Pantai Karanggongso, Kecamatan Watulimo. Telp: 0355-551272. Jumlah kamar: 18.',
            ],

            [
                'nama'           => 'Hotel Hayam Wuruk',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0580,
                'longitude'      => 111.7120,
                'harga_tiket'    => 0,
                'rating'         => 4.5,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Airphone, Restoran, Air Panas, Parkir, Ruang Pertemuan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Hayam Wuruk berlokasi di Jl. Soekarno-Hatta No. 2, Trenggalek. Telp: 0355-792520. Jumlah kamar: 62.',
            ],

            [
                'nama'           => 'Hotel Widowati',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0610,
                'longitude'      => 111.7110,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Restoran',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Widowati berlokasi di Jl. Soekarno-Hatta No. 20, Trenggalek. Telp: 0355-791109. Jumlah kamar: 36.',
            ],

            [
                'nama'           => 'Hotel Gotong Royong',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0600,
                'longitude'      => 111.7120,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Wartel, Hall',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Gotong Royong berlokasi di Jl. Dewi Sartika No. 2, Trenggalek. Telp: 0355-791645. Jumlah kamar: 32.',
            ],

            [
                'nama'           => 'Hotel Ratu Panggul',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3200,
                'longitude'      => 111.6000,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Ruang Pertemuan, Restoran, Parkir',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Ratu Panggul berlokasi di Kecamatan Panggul, Trenggalek. Jumlah kamar: 20.',
            ],

            [
                'nama'           => 'Hotel Bukit Jaas Permai',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0540,
                'longitude'      => 111.7090,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Restoran',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Bukit Jaas Permai berlokasi di Jl. Mayjend Sungkono No. 1, Trenggalek. Telp: 0822 4513 0437. Jumlah kamar: 100.',
            ],

            [
                'nama'           => 'Hotel Atriaz',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0620,
                'longitude'      => 111.7140,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Atriaz berlokasi di Jl. Panglima Sudirman 125, Trenggalek. Telp: 0355-7690838. Jumlah kamar: 29.',
            ],

            [
                'nama'           => 'Penginapan Purnama',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3100,
                'longitude'      => 111.5900,
                'harga_tiket'    => 0,
                'rating'         => 4.1,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan Purnama berlokasi di Desa Wonocoyo, Kec. Panggul. Jumlah kamar: 11.',
            ],

            [
                'nama'           => 'Penginapan Kuda Laut',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4400,
                'longitude'      => 111.5100,
                'harga_tiket'    => 0,
                'rating'         => 4.0,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan Kuda Laut berlokasi di Kecamatan Munjungan. Jumlah kamar: 6.',
            ],

            [
                'nama'           => 'Penginapan Sinar Guru',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4420,
                'longitude'      => 111.5080,
                'harga_tiket'    => 0,
                'rating'         => 4.0,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan Sinar Guru berlokasi di Kecamatan Munjungan. Jumlah kamar: 14.',
            ],

            [
                'nama'           => 'Hotel Pondok Konang',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3380,
                'longitude'      => 111.6090,
                'harga_tiket'    => 0,
                'rating'         => 4.1,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Pondok Konang berlokasi di Desa Nglebeng, Kec. Panggul. Jumlah kamar: 15.',
            ],

            [
                'nama'           => 'Hotel Karanggongso',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Watulimo',
                'latitude'       => -8.2862,
                'longitude'      => 111.7224,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Karanggongso berlokasi di Desa Tasikmadu, Kec. Watulimo. Telp. 0822 3189 6241. Jumlah kamar: 15.',
            ],

            [
                'nama'           => 'Peginapan KPRI Sinar Baru',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4450,
                'longitude'      => 111.5060,
                'harga_tiket'    => 0,
                'rating'         => 4.0,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan KPRI Sinar Baru berlokasi di Munjungan. Jumlah kamar: 16.',
            ],

            [
                'nama'           => 'Hotel Moro Seneng',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0650,
                'longitude'      => 111.7160,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, Kipas Angin, TV',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Moro Seneng berlokasi di Jl. Soekarno-Hatta Gg. Apel No. 13, Kelutan, Trenggalek. Telp: 082 254 900 089. Jumlah kamar: 27.',
            ],

            [
                'nama'           => 'Hotel Sanra',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.2710,
                'longitude'      => 111.5110,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, Smart TV, Wastafel, Water Heater, Shower',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Hotel Sanra berlokasi di Dsn. Bendogolor 36/10, Desa Wonocoyo, Kec. Panggul. Telp: 081 249 909 722. Jumlah kamar: 30.',
            ],

            [
                'nama'           => 'Omah Blado Resort',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4500,
                'longitude'      => 111.4950,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'AC, TV, Water Heater',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Omah Blado Resort berlokasi di Desa Masaran, Kec. Munjungan. Telp: 0851 2985 9497. Jumlah kamar: 8.',
            ],

            [
                'nama'           => 'Penginapan Sinar Gunu',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3600,
                'longitude'      => 111.5800,
                'harga_tiket'    => 0,
                'rating'         => 4.0,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan Sinar Gunu berlokasi di kawasan Panggul, dekat Pantai Kili-Kili.',
            ],

            [
                'nama'           => 'Penginapan Kuda Bali',
                'kategori'       => 'Hotel',
                'kecamatan'      => 'Munjungan',
                'latitude'       => -8.4350,
                'longitude'      => 111.5150,
                'harga_tiket'    => 0,
                'rating'         => 4.0,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '23:59',
                'fasilitas'      => 'Fan',
                'hotel_terdekat' => '-',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Penginapan Kuda Bali berlokasi di Munjungan, dekat kawasan pantai.',
            ],

            // ============================================================
            // KULINER / WISATA KULINER
            // ============================================================

            [
                'nama'           => 'Bu Sihir (Nasi Pecel)',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0580,
                'longitude'      => 111.7130,
                'harga_tiket'    => 0,
                'rating'         => 4.5,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '15:00',
                'fasilitas'      => 'Nasi Pecel',
                'hotel_terdekat' => 'Hotel Hayam Wuruk, Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Bu Sihir berlokasi di Jl. P. Sudirman, Trenggalek. Menu khas: Nasi Pecel. Jam buka: 07.00-15.00.',
            ],

            [
                'nama'           => 'Warung Mbah Suti',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Tugu',
                'latitude'       => -8.0430,
                'longitude'      => 111.7060,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '00:00',
                'jam_tutup'      => '12:00',
                'fasilitas'      => 'Nasi Pecel tradisional',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Warung Mbah Suti berlokasi di Ngantru, Tugu, Trenggalek. Menu khas: Nasi Pecel. Jam buka: 00.00-12.00.',
            ],

            [
                'nama'           => 'Mekar Sari',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0570,
                'longitude'      => 111.7120,
                'harga_tiket'    => 0,
                'rating'         => 4.5,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Sop Buntut, aneka menu keluarga',
                'hotel_terdekat' => 'Hotel Hayam Wuruk, Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Mekar Sari berlokasi di Jl. P. Sudirman, Trenggalek. Menu khas: Sop Buntut. Jam buka: 08.00-21.00.',
            ],

            [
                'nama'           => 'Ayam Goreng Jogja',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0565,
                'longitude'      => 111.7142,
                'harga_tiket'    => 0,
                'rating'         => 4.6,
                'jam_buka'       => '10:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Ayam Goreng',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Ayam Goreng Jogja berlokasi di Jl. Jaksa Agung Suprapto, Trenggalek. Menu khas: Ayam Goreng. Jam buka: 10.00-21.00.',
            ],

            [
                'nama'           => 'Madona',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0610,
                'longitude'      => 111.7100,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '09:00',
                'jam_tutup'      => '00:00',
                'fasilitas'      => 'Pindang Sapi',
                'hotel_terdekat' => 'Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Madona berlokasi di Ds. Bendorejo, Trenggalek. Menu khas: Pindang Sapi. Jam buka: 09.00-24.00.',
            ],

            [
                'nama'           => 'Pak Usup',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0630,
                'longitude'      => 111.7180,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '22:00',
                'fasilitas'      => 'Ayam Lodho',
                'hotel_terdekat' => 'Hotel Widowati',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Pak Usup berlokasi di Ds. Kedunglurah, Trenggalek. Menu khas: Ayam Lodho. Jam buka: 07.00-22.00.',
            ],

            [
                'nama'           => 'Arimbi',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0625,
                'longitude'      => 111.7165,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '17:00',
                'fasilitas'      => 'Aneka Menu',
                'hotel_terdekat' => 'Hotel Widowati',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Arimbi berlokasi di Ds. Dermosari, Trenggalek. Menu khas: Aneka Menu. Jam buka: 08.00-17.00.',
            ],

            [
                'nama'           => 'Warung Malidi',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0640,
                'longitude'      => 111.7190,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '07:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Nasi Pecel',
                'hotel_terdekat' => 'Hotel Widowati',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Warung Malidi berlokasi di Surondakan, Trenggalek. Menu khas: Nasi Pecel. Jam buka: 07.00-21.00.',
            ],

            [
                'nama'           => 'Mbah Temin',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Tugu',
                'latitude'       => -8.0430,
                'longitude'      => 111.7060,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Gurami Bakar',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Mbah Temin berlokasi di Tugu, Trenggalek. Menu khas: Gurami Bakar. Jam buka: 08.00-21.00.',
            ],

            [
                'nama'           => 'Bojana Rasa',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0555,
                'longitude'      => 111.7135,
                'harga_tiket'    => 0,
                'rating'         => 4.4,
                'jam_buka'       => '09:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Ayam Lodho',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Bojana Rasa berlokasi di Kelutan, Trenggalek. Menu khas: Ayam Lodho khas Jawa Timur. Jam buka: 09.00-21.00.',
            ],

            [
                'nama'           => 'Bu Parti',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Karangan',
                'latitude'       => -8.0820,
                'longitude'      => 111.7640,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Nasi Rames',
                'hotel_terdekat' => 'Hotel Hayam Wuruk',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Bu Parti berlokasi di Karangan, Trenggalek. Menu khas: Nasi Rames. Jam buka: 08.00-21.00.',
            ],

            [
                'nama'           => 'Sate Roso Lego',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Trenggalek',
                'latitude'       => -8.0612,
                'longitude'      => 111.7102,
                'harga_tiket'    => 0,
                'rating'         => 4.3,
                'jam_buka'       => '09:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Sate Kambing',
                'hotel_terdekat' => 'Hotel Atriaz',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Sate Roso Lego berlokasi di Ds. Bendorejo, Trenggalek. Menu khas: Sate Kambing. Jam buka: 09.00-21.00.',
            ],

            [
                'nama'           => 'Tanjung Benua',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3100,
                'longitude'      => 111.5900,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Kikil Sapi',
                'hotel_terdekat' => 'Hotel Ratu Panggul',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Tanjung Benua berlokasi di Panggul, Trenggalek. Menu khas: Kikil Sapi. Jam buka: 08.00-21.00.',
            ],

            [
                'nama'           => 'Pojok Loji',
                'kategori'       => 'Kuliner',
                'kecamatan'      => 'Panggul',
                'latitude'       => -8.3120,
                'longitude'      => 111.5920,
                'harga_tiket'    => 0,
                'rating'         => 4.2,
                'jam_buka'       => '08:00',
                'jam_tutup'      => '21:00',
                'fasilitas'      => 'Nasi Campur',
                'hotel_terdekat' => 'Hotel Ratu Panggul',
                'gambar'         => 'default.jpg',
                'deskripsi'      => 'Pojok Loji berlokasi di Panggul, Trenggalek. Menu khas: Nasi Campur. Jam buka: 08.00-21.00.',
            ],
             
                
        ];

        foreach ($data as $item) {
            Wisata::create($item);
        }
    }
}